services:
  postgres-db:
    image: postgres:16-alpine
    container_name: financeai_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - financeai-net

  # Mock obsoleto desplazado al puerto 8001
  mock-api:
    build: ./mock-api
    container_name: financeai_mock_api
    ports:
      - "8001:8001"
    networks:
      - financeai-net

  # Nuevo motor de IA real (Canónico)
  modelo-financeai:
    build: ./data-science/modeloFinanceAI
    container_name: financeai_modelo
    ports:
      - "8000:8000"
    networks:
      - financeai-net

  backend:
    build: ./backend
    container_name: financeai_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - modelo-financeai
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      IA_API_URL: ${IA_API_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    networks:
      - financeai-net

volumes:
  postgres_data:

networks:
  financeai-net:
    driver: bridge