services:
  postgres-db:
    image: postgres:16-alpine
    container_name: financeai_postgres
    environment:
      POSTGRES_DB: financeai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mock-api:
    build: ./mock-api
    container_name: financeai_mock_api
    ports:
      - "8001:8001"

  modelo-financeai:
    build: ./data-science/modeloFinanceAI
    container_name: financeai_modelo_Data-Science
    ports:
      - "8000:8000"

  backend:
    build: ./backend
    container_name: financeai_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - modelo-financeai
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/financeai_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
      JWT_EXPIRATION: 86400000

      IA_API_URL: http://modelo-financeai:8000

      # Entorno local
      OPENAPI_SERVER_URL: http://localhost:8080

      # Solo para despliegue en OCI:
      # OPENAPI_SERVER_URL: https://myfinanceai.duckdns.org

volumes:
  postgres_data: