spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JWT (Busca la variable de entorno; si no existe, usa la clave local de desarrollo)
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Desactivar advertencia de OSIV en JPA
spring.jpa.open-in-view=false