spring:
  application:
    name: financeai

server:
  forward-headers-strategy: framework

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false # Resuelve el hallazgo AUD-11

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

ia:
  api:
    url: ${IA_API_URL}

app:
  openapi:
    server-url: ${APP_OPENAPI_SERVER_URL:http://localhost:8080}

# Configuración de Logs para depuración local
logging:
  level:
    org.springframework.web: INFO
    com.nocountry.financeai: DEBUG
    # Muestra los valores reales inyectados en las sentencias SQL de Hibernate
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE